### DISCUSSION TITLE
Omitted translations with unclear reason

### DISCUSSION THREAD

**Discussion by alpha-khambir** [crowdin/crowdin-cli#609] [Q&A] [answered]
Hello 👋

I try to configure fetching translations, but there is an error:
```
Due to missing respective sources, the following translations will be omitted:
	- es-ES/Foo/Resources/en.lproj/Localizable.strings
```

My crowdin.yml:
```
"project_id": "---"
"api_token": "---"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    "source": "/Foo/Resources/en.lproj/Localizable.strings",
    "translation": "/Foo/Resources/%osx_code%/%original_file_name%",
  }
]
```

My source:
<img width="481" alt="image" src="https://github.com/crowdin/crowdin-cli/assets/93246264/933f2b68-c10a-48bf-9d91-a0c79ecb7750">

<img width="686" alt="image" src="https://github.com/crowdin/crowdin-cli/assets/93246264/24c4a6c5-646d-4483-bc20-59bcd3c5a965">

My paths:
`Foo/Resources/en.lproj/Localizable.strings`
`Foo/Resources/es.lproj/Localizable.strings`

What am I doing wrong? @andrii-bodnar may you help?

**Comment by andrii-bodnar** [comment, marked as answer]
Hi @alpha-khambir,

please try to specify a [Languages Mapping](https://crowdin.github.io/crowdin-cli/advanced#languages-mapping-configuration) for the Spanish language:

```yml
"project_id": "---"
"api_token": "---"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    "source": "/Foo/Resources/en.lproj/Localizable.strings",
    "translation": "/Foo/Resources/%osx_code%/%original_file_name%",
    "languages_mapping": {
      "osx_code": {
        "es-ES": "es.lproj"
      }
    }
  }
]
```
