### ISSUE TITLE
Ignore filter not being applied to translations on upload

### ISSUE THREAD

**Issue by mbrookes** [crowdin/crowdin-cli#100]
We have the following configuration file, working with github sync:
```
files:
  - source: /docs/src/**/*.md
    ignore:
      - /**/%file_name%-%two_letters_code%.md
      - /docs/src/pages/getting-started/page-layout-examples/**/*
      - /docs/src/pages/premium-themes/**/*
    translation: /%original_path%/%file_name%-%two_letters_code%.%file_extension%
  - source: /docs/translations/*.json
    ignore:
      - /**/%file_name%-%two_letters_code%.json
    translation: /%original_path%/%file_name%-%two_letters_code%.%file_extension%

```
(Original: https://github.com/mui-org/material-ui/blob/next/crowdin.yml)

However, on running `crowdin upload --dryrun` while in the project root directory, it indicates that it would upload all files, including translations:
```
src/modules/components/backers-de.md
src/modules/components/backers-es.md
src/modules/components/backers-fr.md
src/modules/components/backers-ja.md
src/modules/components/backers-pt.md
src/modules/components/backers-ru.md
src/modules/components/backers-zh.md
src/modules/components/backers.md
src/pages/css-in-js/advanced/advanced-de.md
src/pages/css-in-js/advanced/advanced-es.md
src/pages/css-in-js/advanced/advanced-fr.md
src/pages/css-in-js/advanced/advanced-ja.md
src/pages/css-in-js/advanced/advanced-pt.md
src/pages/css-in-js/advanced/advanced-ru.md
src/pages/css-in-js/advanced/advanced-zh.md
src/pages/css-in-js/advanced/advanced.md
[etc...]
```
In addition, as well as wanting to upload the translations, it appears to want to upload all source files new, changed and existing, rather than just new or changed files.

Thanks.
