### ISSUE TITLE
BC break with configuration file v1

### ISSUE THREAD

**Issue by nclavaud** [crowdin/crowdin-cli#23]
Hello,

We have been using crowdin and crowdin-cli (v1) for a long time now. I have tried running crowdin-cli-2 but it somehow broke our project.

Running `crowdin lint` looks OK:
```
$ crowdin lint
Your configuration file looks to be good
```

However, the behavior of `crowdin upload sources` is not what was expected. We ended up with a lot of new files on the project tree (whereas just one file was really new) without respect to the directory hierarchy. It looks like `preserve_hierarchy` is set to `true` by default in v1, and `false` in v2.

I feel like backward compatibility is broken when using crowdin-cli 2 with a v1 config file (that gets validated nonetheless).

Do you have any plan to distinguish between v1/v2 config files - something like a `version: 2` key maybe? Or anything else to keep the behavior consistent between the two versions?

**Comment by ihor-popyk** [comment]
Hello @nclavaud !
I'm sorry, for these problems with CLI. Will do all best to make CLI great.
1) `preserve_hierarchy` is `false` default in both v1 and v2
2) also you still can use `old-style config` in both CLIs, or `new json-style`, but only in CLI v2

Please send me your configuration file so that I could help you more

**Comment by nclavaud** [comment]
Thanks for your quick feedback @ihor-popyk.

You will find our configuration file below.

Using crowdin-cli v1, local file `ff-ZA/back/pdf/invoice.csv` will be uploaded at `back/pdf/invoice.csv`.
Using crowdin-cli v2, local file `ff-ZA/back/pdf/invoice.csv` will be uploaded at `pdf/invoice.csv`.

```
project_identifier: xxx
api_key: xxx

files:
-
    source: 'ff-ZA/front/**/*.csv' #takes all json underneath front/ 
    scheme: 'identifier,source_or_translation,context'
    multilingual_spreadsheet: false
    translation: '/%locale%/front/**/%original_file_name%' #writes all with same path underneath front/
    update_option: 'update_as_unapproved'
-
    source: 'ff-ZA/back/**/*.csv' #takes all csv underneath back/
    scheme: 'identifier,source_or_translation,context'
    multilingual_spreadsheet: false
    translation: '/%locale%/back/**/%original_file_name%' #writes all with the same path underneath back/
    update_option: 'update_as_unapproved'
-
    source: 'ff-ZA/pages/**/*.csv' #takes all csv underneath pages/
    scheme: 'identifier,source_or_translation,context'
    multilingual_spreadsheet: false
    translation: '/%locale%/pages/**/%original_file_name%' #writes all with the same path underneath pages/
    update_option: 'update_as_unapproved'
-
    source: 'ff-ZA/pages/**/*.html' #takes all html underneath pages/
    translation: '/%locale%/pages/**/%original_file_name%' #writes all with the same path underneath pages/
    update_option: 'update_as_unapproved'
-
    source: 'ff-ZA/back/email/*.txt' #takes all txt underneath back/email/
    translation: '/%locale%/back/email/%original_file_name%' #writes all with the same path underneath back/email
    update_option: 'update_as_unapproved'
-
    source: 'ff-ZA/back/email/*.html' #takes all txt underneath back/email/
    translation: '/%locale%/back/email/%original_file_name%' #writes all with the same path underneath back/email
    update_option: 'update_as_unapproved'
-
    source: 'ff-ZA/back/pdf/*.txt' #takes all txt underneath back/pdf/
    translation: '/%locale%/back/pdf/%original_file_name%' #writes all with the same path underneath back/pdf
    update_option: 'update_as_unapproved'
```
