### ISSUE TITLE
language_mapping doesn't work for %locale% placeholder

### ISSUE THREAD

**Issue by erickskrauch** [crowdin/crowdin-cli#277]
**Describe the bug**
I'm trying to set up Google Play's changelogs translation. In most cases, [Google prefer the full dashed locale code](https://support.google.com/googleplay/android-developer/answer/113469?hl=en) (e.g. en-US), but in some cases, they require the two-letter code (`th`, `lv`, `fil`). I have the next configuration:

```
files:
  - source: /fastlane/metadata/android/en-US/changelogs/default.txt
    dest: /android/default-changelog.txt
    translation: /fastlane/metadata/android/%locale%/changelogs/default.txt
    languages_mapping:
      locale:
        th-TH: th
```

But it doesn't do anything.

**To Reproduce**
1. Configuration file: *above*
2. Execute CLI command: `crowdin download`
3. See that translations are still downloaded to the `th-TH` folder rather than `th`, defined in the `languages_mapping` setting.

**Expected behavior**
All locales should be stored in their `%locale%` folders, but `th-TH` should be mapped to the `th` directory.

**Environment:**
 - OS: MacOS
 - Version: 10.14.6
- CLI: 3.1.15

**Screenshots**
![](https://erickskrauch.ely.by/monosnap-02-07-2020-at-19-34-49.png)
