### ISSUE TITLE
Crowdin cli returns null on most commands.

### ISSUE THREAD

**Issue by fr33l** [crowdin/crowdin-cli#303]
**Describe the bug**
Crowdin cli returns `null` on most commands

**To Reproduce**
```
project_id: 11111
api_token: 1111111111
base_path:
preserve_hierarchy: true
files:
- source: /project/locale/django.pot
  translation: /project/locale/%two_letters_code%/LC_MESSAGES/django.po
  languages_mapping:
    two_letters_code:
      pt-BR: pt_BR
```
2. Execute CLI command: crowdin upload sources -b test_translate -v
3. See an error:
```❌ null```

**Expected behavior**
Upload sources to crowdin branch

**Environment:**
 - OS:  Ubuntu
 - Version 18.04
- Crowdin 3.2.1

**Additional context**
Older versions like 2.0.31 seem to work just fine. I assume this is related to your latest API changes. I've tried using both `api_token` and `api_key` with new crowdin cli, both return the same result.
