### ISSUE TITLE
Unable to find some local files

### ISSUE THREAD

**Issue by sylvaindeloux** [crowdin/crowdin-cli#349]
**Describe the bug**
I can't load local files to push them to Crowdin.

**To Reproduce**
Configuration file:
```
project_id: "xxx"
api_token: "xxx"
base_path: "xxx"
base_url: "https://api.crowdin.com"
preserve_hierarchy: "true"

files:
    -
        source: "/translations/messages+intl-icu.en.yaml"
        translation: "/translations/build/messages+intl-icu.%two_letters_code%.yaml"
    -
        source: "/translations/admin+intl-icu.en.yaml"
        translation: "/translations/build/admin+intl-icu.%two_letters_code%.yaml"
```

Execute cli command:
```
crowdin push
```

See an error:
```
✔️  Fetching project info
❌ No sources found for '/translations/messages+intl-icu.en.yaml' pattern. Check the source paths in your configuration file
❌ No sources found for '/translations/admin+intl-icu.en.yaml' pattern. Check the source paths in your configuration file
❌ Current execution finished with errors
```

**Expected behavior**
The files are present and valid, so the `push` command should detect them.

**Environment:**
 - OS: macOS 11.2.1
 - Crowdin CLI 3.5.4

**Additional context**
When using `source: "/translations/*.yaml"` syntax, the files are found, but that's not the expected behavior.
