### ISSUE TITLE
`skip_untranslated_strings` broken when used with FBT

### ISSUE THREAD

**Issue by alexandernanberg** [crowdin/crowdin-cli#353]
**Describe the bug**

When using the `skip_untranslated_strings` in a fbt project, the downloaded translations are not valid and fbt throws an exception when trying to parse them.

**To Reproduce**

1. Configuration file: 
```yml
'base_path': '.'
'base_url': 'https://api.crowdin.com'
'preserve_hierarchy': true

files:
  [
    {
      'source': '/i18n/source_strings.json',
      'translation': '/i18n/locales/%locale_with_underscore%.json',
      'dest': '/source_strings.json',
      'escape_special_characters': 0,
    },
  ]

```
2. Add a new source string and run `crowdin push`
3. `crowdin pull`
3. Downloaded file will contain
```json5
{
  // other translations ...
  "3FXDlC5vnE/y+OZSJXr+IQ==": null
}
```

**Expected behavior**

The key should be omitted not set to `null`

```json5
{
  // other translations...
}
```

**Environment:**
 - OS: MacOS
 - Version 11.2
 
**Screenshots**
N/A

**Additional context**
N/A
