### ISSUE TITLE
Archive with translations is not being extracted

### ISSUE THREAD

**Issue by ixcviw7bw** [crowdin/crowdin-cli#367]
**Describe the bug**
Crowdin CLI does not output any files when downloading translations.

**To Reproduce**
1. Configuration file:
```yaml
"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files:
  [
    {
      "source": "/src/locales/en/*.json",
      "translation": "/src/locales/%two_letters_code%/%original_file_name%",
    },
  ]

```
(I've also tried /resources/ instead of /src/locales/ and %locale% instead of %two_letters_code%)

2. File structure: 
<img width="145" alt="Screenshot at Jun 08 03-44-34" src="https://user-images.githubusercontent.com/5052636/121109463-e9583680-c80b-11eb-8788-24edd9ad1af3.png">

3. Execute CLI command: `crowdin download --verbose --all` (or just `crowdin download`)

4. See see a successful message, but nothing written under `/src/locales/`

```
✔️  Fetching project info     
✔️  Building ZIP archive with the latest translations
✔️  Building translation (100%)
✔️  Downloading translation     
✔️  Extracting archive   
```
Exit code 0

**Expected behavior**
Translated files should be written under /src/locales/

**Environment:**
 - Mac OS 11.4, 20F71
 - M1
 - OpenJDK 16.0.1

**Additional context**

Crowdin CLI is downloading an archive with translations. It is writing it to a temporary file, silently fails to extract it, and deletes the archive. I was able to capture this file by keeping a command running while Crowdin CLI is working. It waits for temporary file and copies it before Crowdin CLI deletes it:

```bash
while true; do cp ./CrowdinTranslations* "captured_$(date +%s).zip" 2>/dev/null && break; done
```

After extracting the captured archive manually, its contents appear to be correct:

<img width="204" alt="Screenshot at Jun 08 04-01-56" src="https://user-images.githubusercontent.com/5052636/121111001-71d7d680-c80e-11eb-8a24-074731b82319.png">

So it appears that extraction silently fails, but everything else is working.

Might be related to #122
