### ISSUE TITLE
[3.7.8] Problems with source files that have dot at the begin

### ISSUE THREAD

**Issue by dragomano** [crowdin/crowdin-cli#440]
**Describe the bug**
`source` parameter does not see a file exists, if a file has double extension

**To Reproduce**
1. Configuration file:
```
project_id: <hidden>
api_token: <hidden>
base_path : ".."
base_url : "https://api.crowdin.com"
preserve_hierarchy: true

files: [
  {
    source: "/**/.english.php",
    translation: "%original_path%/.%language%.php"
  }
]

```
3. Execute CLI command:
```
crowdin upload sources --dryrun --config .github/crowdin.yml
```
5. Result:
```
[OK] Fetching project info
```

**Expected behavior**
I would like to see this result:
```
[OK] Fetching project info
[OK] File '.english.php'
```

**Environment:**
 - OS: Windows 11 x64
 - Version 21H2

**Comment by andrii-bodnar** [comment]
Hi @dragomano!

Is this issue only reproducible on the 3.7.8 version or on the previous versions also?

**Comment by dragomano** [comment]
Yes, the same problem.

config.yml
```yml
project_id: <hidden>
api_token: <hidden>
base_path : "."
base_url : "https://api.crowdin.com"
preserve_hierarchy: true

files: [
  {
    source: "/**/.english.php",
    translation: "%original_path%/.%language%.php"
  }
]

```
