### ISSUE TITLE
Cant upload translations via CLI

### ISSUE THREAD

**Issue by ivan-gaydamakin** [crowdin/crowdin-cli#445]
**Describe the bug**
When I tried to upload translations with `dest: /Apps/**/WhiteLabel.strings`  , cli don't correctly make path
Without ** - all ok

And give this error:
```
✔️  Fetching project info    
❌ Failed to upload translations for the source 'Apps/Wallester/Application/Localisables/Base.lproj/WhiteLabel.strings' since file 'WA-7767/Apps/Wallester/Application/Localisables/Base.lproj/WhiteLabel.strings' is missing in the project. Run the 'crowdin push' to upload the missing source
❌ Current execution finished with errors
```

Have this bug with branch or without it

**To Reproduce**
- make crowdin.yml:
```
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true

files:
  - source: /Apps/**/Application/Localisables/Base.lproj/WhiteLabel.strings
    translation: /Apps/**/Application/Localisables/%two_letters_code%.lproj/%original_file_name%
    dest: /Apps/**/WhiteLabel.strings

  - source: /Apps/Common/Localisables/Base.lproj/InfoPlist.strings
    translation: /Apps/Common/Localisables/%two_letters_code%.lproj/%original_file_name%
    dest: /Apps/Common/%original_file_name%
```
- make sync via github integration  
- exec command `crowdin upload translations -b WA-7767`

**Expected behavior**
Same path in dest like `/Apps/Wallester/WhiteLabel.strings`,`/Apps/SecondApp/WhiteLabel.strings`

**Environment:**
 - OS: MacOs
 - Version 12.3.1
 - Crowdin-cli: 3.7.8

**Screenshots**
Synced Content:
![image](https://user-images.githubusercontent.com/84778353/165718350-e32f2ead-90f9-4274-af55-46d80d245239.png)

**Additional context**
If I manually show him my `Apps`, they good how I want.

Example:
```
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true

files:
  - source: /Apps/Wallester/Application/Localisables/Base.lproj/WhiteLabel.strings
    translation: /Apps/Wallester/Application/Localisables/%two_letters_code%.lproj/%original_file_name%
    dest: /Apps/Wallester/WhiteLabel.strings
  - source: /Apps/Common/Localisables/Base.lproj/InfoPlist.strings
    translation: /Apps/Common/Localisables/%two_letters_code%.lproj/%original_file_name%
    dest: /Apps/Common/%original_file_name%
```

**Comment by andrii-bodnar** [comment]
Hi @ivan-gaydamakin!

Please try to change the `dest` parameter in the first filegroup in your `crowdin.yml` configuration file:

`dest: /Apps/**/WhiteLabel.strings` -> `dest: /Apps/Wallester/WhiteLabel.strings`

because this pattern is not matching the files structure in Crowdin - CLI will build the dest path including subfolders (**)

**Comment by ivan-gaydamakin** [comment]
oh... that is bad, we just have not only Wallester in Apps folder, we also have SomeApp1, SomeApp2, and for every app, make update crowdin.yml, it's not good :(

And this "**" work well when I just use `download`

**Comment by andrii-bodnar** [comment]
The thing is that `/Apps/Wallester/WhiteLabel.strings` not equal `dest: /Apps/**/WhiteLabel.strings`. This is the reason why CLI can't find files to upload translations.

To make it work correctly, the config might look like this:

```
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true

files:
  - source: /Apps/**/Application/Localisables/Base.lproj/*.strings
    translation: /Apps/**/Application/Localisables/%two_letters_code%.lproj/%original_file_name%
```

But this config requires sources re-upload in Crowdin. Also, the files structure after upload will be different. You can also try `preserve_hierarchy: false` in this case - it will not upload some sub-folders.
