### ISSUE TITLE
Enable mixture of `%locale%` and `%two_letters_code%` downloads

### ISSUE THREAD

**Issue by lorenzolewis** [crowdin/crowdin-cli#456]
**Is your feature request related to a problem? Please describe.**
When we have Chinese Traditional and Chinese Simplified enabled in our Crowdin project, this creates a conflict for two letter language codes (you can also see this with Portuguese). We would like to allow Crowdin to download whichever format is shown in the UI of Crowdin (so we could have folder structures like `en`, `zh-CN`, etc. all handled).

**Describe the solution you'd like**
Offer another placeholder in the CLI/config file (https://developer.crowdin.com/configuration-file/#placeholders) to handle placing translations in whatever naming convention they show in the UI.

**Describe alternatives you've considered**
Manual mapping via Crowdin UI: This requires manual work which no one likes :)

We don't want to over-write the existing functionality of how `%locale%` and `%two_letters_code%` work.

**Additional context**
N/A

**Comment by andrii-bodnar** [comment]
Hi @lorenzolewis,

Instead of manually mapping languages via Crowdin UI there is a possibility to map languages using the CLI config also.

For example:

```yml
"files": [
  {
    "source": "/lang/en.json",
    "translation": "/lang/%locale%.json",
    "languages_mapping": {
      "locale": {
        "ar": "ar",
        "uk": "uk",
        "vi": "vi",
        "pt-BR": "pt-BR",
        "pt-PT": "pt-PT",
        "zh-CN": "zh-CN",
        "zh-TW": "zh-TW"
      }
    }
  }
]

```

```yml
files:
  - source: /src/i18n/locales/en-US.json
    translation: /src/i18n/locales/%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        nl-BE: nl-BE
        pt-BR: pt-BR
        zh-CN: zh-HANS
        zh-TW: zh-HANT
```

As a key, there should be used the [Crowdin language code](https://support.crowdin.com/api/language-codes/) and as a value - your code.
