### ISSUE TITLE
Empty strings when using `skip_untranslated_strings`

### ISSUE THREAD

**Issue by elvis-pereira** [crowdin/crowdin-cli#457]
**Describe the bug**
I'm having the exact same problem described in #428. I updated my config file to use the `skip_untranslated_strings: true` option, however when I run the `crowdin download -b master` command the download files come with a bunch of empty strings where there is no translation yet.

**To Reproduce**
GitLab repository: https://gitlab.com/fvtt-brasil/pf2e
Crowdin project: https://fvtt.crowdin.com/pf2e
1. Configuration file:
```yml
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: https://fvtt.crowdin.com

preserve_hierarchy: false

commit_message: "chore(crowdin): new translations %original_file_name% from Crowdin"
append_commit_message: false

files:
  [
    {
      source: /pf2e_pt-BR/lang/en/*.json,
      translation: /pf2e_pt-BR/lang/%locale%/compendium/pf2e.%original_file_name%,
      ignore: [/pf2e_pt-BR/lang/en/en.json, /pf2e_pt-BR/lang/en/re-en.json],
      skip_untranslated_strings: true
    },
    {
      source: /pf2e_pt-BR/lang/en/en.json,
      translation: /pf2e_pt-BR/lang/%locale%/system.json,
      skip_untranslated_strings: true
    },
    {
      source: /pf2e_pt-BR/lang/en/re-en.json,
      translation: /pf2e_pt-BR/lang/%locale%/rules-elements.json,
      skip_untranslated_strings: true
    },
  ]
```
2. Execute CLI command: `crowdin download -b master`
3. Files are downloaded correctly, but every term without a translation yet comes as `"translation-key": ""`

**Expected behavior**
Terms without translations should not be present, instead of coming with an empty string.

**Environment:**
 - OS: Arch Linux
 - Crowdin CLI version 3.7.8 (installed though NPM/PNPM)
