### ISSUE TITLE
Failed to download Multilingual file translations with the dest parameter

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#486]
**Describe the bug**

The `dest` parameter is not working for the multicolumn spreadsheet translations downloading.

**To Reproduce**

1. `crowdin.yml` configuration file:

```yml
"project_id" : "-ID-"
"api_token" : "-TOKEN-" 
"base_path" : "."
"base_url" : "https://crowdin.com"

"preserve_hierarchy": true

files: [ 
 {
    "source": "strings.csv",
    "dest": "dir/strings.csv",
    "translation": "strings.csv",
    "first_line_contains_header": true,
    "scheme": "identifier,source_phrase,de,es-ES,fr,ja,ko,pt-PT,zh-CN"
  }
]
```

2. The `strings.csv` file content:

```csv
"","source_phrase","de","es","fr","ja","ko","pt","zh"
"identifier.1","test string 1","","","","","","",""
"identifier.2","test string 2","","","","","","",""
"identifier.3","test string 3","","","","","","",""
"identifier.4","test string 4","","","","","","",""
```

4. Execute CLI command: `crowdin push` (to upload source file to the Crowdin project)
5. Execute CLI command: `crowdin pull`
6. See an error

If you remove the `dest` parameter - everything is working as expected (requires sources reupload)

**Expected behavior**

Successfully downloaded translations.

**Environment:**
 - OS: MacOS, Ubuntu, Windows
 - Version: CLI latest version

**Screenshots**

![image](https://user-images.githubusercontent.com/29282228/193771667-267aca85-8fee-4d7b-b5f2-c213510d3c44.png)

**Additional context**

[The `dest` option description](https://developer.crowdin.com/configuration-file/#uploading-files-to-specified-path-with-specified-type)
[Multicolumn Spreadsheet](https://developer.crowdin.com/configuration-file/#multicolumn-spreadsheet)
