### ISSUE TITLE
You do not have permission to view/edit project with provided id.

### ISSUE THREAD

**Issue by kimmy-wang** [crowdin/crowdin-cli#529]
**Describe the bug**
You do not have permission to view/edit project with provided id.

**To Reproduce**
1. Configuration file: '...'
2. Execute CLI command: '...'
3. See an error

**Expected behavior**

**Environment:**
 - OS: macos
 - Version [e.g. 18.04]

**Screenshots**
![截屏2023-01-19 11 42 34](https://user-images.githubusercontent.com/19725091/213350120-b781a53c-79f6-4b2d-8111-30583645ca78.png)

**Additional context**
"@crowdin/cli": "^3.9.1",
"@crowdin/crowdin-api-client": "^1.20.1",

```yaml
#
# Your Crowdin credentials
#
project_id: '562293'
api_token_env: CROWDIN_PERSONAL_TOKEN
# base_path: '.'
# base_url: https://api.crowdin.com

#
# Choose file structure in Crowdin
# e.g. true or false
#
preserve_hierarchy: true

# We generally want to use the "two-letters-code" of a locale (ie the language)
# But not for all locales!
# "pt-BR" may be better to remain as "pt-BR" instead of being transformed to "pt"
# Note: &/* is Yaml anchor syntax: https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/
languages_mapping: &languages_mapping
  two_letters_code:
    pt-BR: pt-BR

#
# Files configuration
#
files:
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
    languages_mapping: *languages_mapping
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    languages_mapping: *languages_mapping
  - source: /community/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-community/current/**/%original_file_name%
    languages_mapping: *languages_mapping
  - source: /versioned_docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%
    languages_mapping: *languages_mapping
  - source: /blog/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
    languages_mapping: *languages_mapping
  - source: /src/pages/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-pages/**/%original_file_name%
    ignore: [/**/*.js, /**/*.jsx, /**/*.ts, /**/*.tsx, /**/*.css]
    languages_mapping: *languages_mapping
#
# Source files filter
# e.g. "/resources/en/*.json"
#
#"source" : "/docs/**/*.md",
#
# Where translations will be placed
# e.g. "/resources/docs/%two_letters_code%/%original_file_name%"
#
#"translation" : "/i18n/%language%/docs/current/%original_file_name%",
#
# Files or directories for ignore
# e.g. ["/**/?.txt", "/**/[0-9].txt", "/**/*\?*.txt"]
#
#"ignore" : [],
#
# The dest allows you to specify a file name in Crowdin
# e.g. "/messages.json"
#
#"dest" : "",
#
# File type
# e.g. "json"
#
#"type" : "",
#
# The parameter "update_option" is optional. If it is not set, after the files update the translations for changed strings will be removed. Use to fix typos and for minor changes in the source strings
# e.g. "update_as_unapproved" or "update_without_changes"
#
#"update_option" : "",
#
# Start block (for XML only)
#
#
# Defines whether to translate tags attributes.
# e.g. 0 or 1  (Default is 1)
#
# "translate_attributes" : 1,
#
# Defines whether to translate texts placed inside the tags.
# e.g. 0 or 1 (Default is 1)
#
# "translate_content" : 1,
#
# This is an array of strings, where each item is the XPaths to DOM element that should be imported
# e.g. ["/content/text", "/content/text[@value]"]
#
# "translatable_elements" : [],
#
# Defines whether to split long texts into smaller text segments
# e.g. 0 or 1 (Default is 1)
#
# "content_segmentation" : 1,
#
# End block (for XML only)
#
#
# Start .properties block
#
#
# Defines whether single quote should be escaped by another single quote or backslash in exported translations
# e.g. 0 or 1 or 2 or 3 (Default is 3)
# 0 - do not escape single quote;
# 1 - escape single quote by another single quote;
# 2 - escape single quote by backslash;
# 3 - escape single quote by another single quote only in strings containing variables ( {0} ).
#
# "escape_quotes" : 3,
#
# Defines whether any special characters (=, :, ! and #) should be escaped by backslash in exported translations.
# e.g. 0 or 1 (Default is 0)
# 0 - do not escape special characters
# 1 - escape special characters by a backslash
#
# "escape_special_characters": 0
#
#
# End .properties block
#
#
# Often software projects have custom names for the directories where translations are placed. crowdin-cli allows you to map your own languages to be understandable by Crowdin.
#
#"languages_mapping" : {
#  "two_letters_code" : {
#    "crowdin_language_code" : "local_name"
#   }
#},
#
# Does the first line contain header?
# e.g. true or false
#
#"first_line_contains_header" : true,
#
# for spreadsheets
# e.g. "identifier,source_phrase,context,uk,ru,fr"
#
# "scheme" : "",

```

**Comment by DimaYashchyshyn** [comment]
Hello, what's your role in the project? You need to be at least a manager to perform CLI properly.

**Comment by kimmy-wang** [comment]
Owner

**Comment by kimmy-wang** [comment]
![截屏2023-01-19 12 26 54](https://user-images.githubusercontent.com/19725091/213355025-4a337ecc-59a3-4d62-99e5-2be9bbcc66a9.png)

**Comment by nikzen** [comment]
Hey,

I have the same issue. Crowdin API says that I am not allowed to upload more than three different file types. (I only have two) I created a new project and then did a clean run. Now the Crowdin API says "Internal Server Error".

Thanks for your help

Best, Niklas

**Comment by DimaYashchyshyn** [comment]
Hello @nikzen and @kw214. We found the reason for this behavior, it is related to .mdx file versions, and currently working on a solution. 

Please email us at support@crowdin.com and we will apply a quick fix for you in a timely manner. 

p.s. Niklas, seems you've already emailed us about 10 minutes ago and I've applied the fix, can you confirm all works fine now?

**Comment by nikzen** [comment]
> Hello @nikzen and @kw214. We found the reason for this behavior, it is related to .mdx file versions, and currently working on a solution.
> 
> Please email us at [support@crowdin.com](mailto:support@crowdin.com) and we will apply a quick fix for you in a timely manner.
> 
> p.s. Niklas, seems you've already emailed us about 10 minutes ago and I've applied the fix, can you confirm all works fine now?

You are fast :) For now it is not fixed for me but I am very sure there will be a fix.

Thanks a lot

Best,

Niklas

**Comment by gtnardy** [comment]
I'm looking for a solution to this too! I've started a conversation through e-mail and the fix was applied, but I started getting the errors again.

Looking forward to the definitive solution 🙏

**Comment by Rommka4** [comment]
Hi @gtnardy,
Sorry for the temporary inconvenience, I've temporarily increased the file format limit for you so you don't encounter this error
The task for our developers is created and in progress. As soon as we receive an update on this, we will let you know via email immediately!

As far as I understand, it seems that after some updates regarding the mdx file format, the system started to consider different versions of the MD and MDX file formats as different formats. As a result, you exceed the plan's file format limit and receive an error🥲

Since I've temporarily increased the file format limit for you, you shouldn't have this problem now

**Comment by gtnardy** [comment]
Thank you @Rommka4 for that! 

But I'm not sure if it is the same error reason, but running the cli sync now I get this error for some files:
`<key: storageId, code: fileInvalid, message: This file can't be updated. Please, import the file first.>`

**Comment by Rommka4** [comment]
@gtnardy 
Hmm, sorry for the confusion🙈
I see my colleague created a task about this error, so we will have to wait for updates from the developers🥲
Hope for your understanding and patience

**Comment by tabris233** [comment]
Is there any progress here?

I'm having this problem too.

<img width="703" alt="image" src="https://user-images.githubusercontent.com/29500388/225346526-caaec50c-1f4d-45d5-a57c-4edd46b261eb.png">

```yml
project_id: '573641'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  # JSON 翻译文件
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  # Markdown 文档文件
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  # Markdown 博客文件
  # - source: /blog/**/*
  #   translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%

```
