### ISSUE TITLE
Wrong translations are downloaded

### ISSUE THREAD

**Issue by holdMyTea** [crowdin/crowdin-cli#542]
**Translations are downloaded for the wrong file.**
I have these two files in a project:
- **/Front-end/cabinet/messages.json**
- **/Front-end/order/messages.json**
<img width="516" alt="image" src="https://user-images.githubusercontent.com/16446380/224817725-f3c13bd0-c97e-4f24-9c48-dde6965a7512.png">

They're associated with two different repos, their configs are as follows:

**Cabinet config**

```yml
"project_id": "project_id"
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
 {
  "source" : "lang/en/messages.json",
  "dest": "Front-end/cabinet/%file_name%.json",
  "translation" : "lang/%two_letters_code%/messages.json"
 }
]
```

**Order config**

```yml
'project_id': 'project_id'
'base_url': 'https://api.crowdin.com'
'preserve_hierarchy': true

files:
  [
    {
      'source': 'lang/en/messages.json',
      'dest': 'Front-end/order/%file_name%.json',
      'translation': 'lang/%two_letters_code%/messages.json',
    },
  ]

```
The exact issue is when I execute `crowdin download` command for project with Cabinet config I get translation file for the Order one. The resulting diff from download is a completely new file with 0 matching keys.
While the same command for the second project downloads the same Order file (which is the expected result).

**To Reproduce**
1. **Locally** create two separate folders
2. Put Cabinet config in the first one & Order config in the second one
3. Given you have data to do so push them into Crowdin with `crowdin upload sources`
4. **In Crowdin** add translations for both files
5. **Locally** pull the translations in the Cabinet project with `crowdin download`
6. Compare downloaded translation keys with the source ones

**Expected behavior**
Expect command `crowdin download` to downloa translation files matching sources ones for each supplied config.

**Environment:**
 - OS: macOS
 - Version: Ventura 13.2.1
 - @crowdin/cli: 3.10.1
