### ISSUE TITLE
Translation attribute in crowdin.yml, translation did not preserve the original folder/file hierarchy

### ISSUE THREAD

**Issue by lattechen925** [crowdin/crowdin-cli#579]
**Describe the bug**
`**/%original_file_name%`: the translation did not preserve the original folder/file hierarchy

**To Reproduce**
1. Configuration file: 
```
project_id: '123456'
api_token_env: CROWDIN_PERSONAL_TOKEN
"base_path" : "."
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true,

files: [
  {
    source: '/i18n/**/*',
    translation: '/i18n/%two_letters_code%/**/%original_file_name%'
  }
]
```
i18n directory structure: 
```
i18n/
├── README.md
└── core
    └── guide
       ├── README.md
       ├── intro.md
    └── README.md
```

3. Execute CLI command: 
first
```
crowdin upload sources
```
then
```
crowdin download
```
result
![image](https://github.com/crowdin/crowdin-cli/assets/22408894/7f66730e-e71c-4fc2-9949-920e8dddea9e)

5. See an error

**Expected behavior**
After executing the `crowdin download`, I expect to preserve the original directory structure,such as: 
```

i18n/
├── README.md
└── core
    └── guide
       ├── README.md
       ├── intro.md
    └── README.md
└── zh
    ├── README.md
    └── core
    └── guide
       ├── README.md
       ├── intro.md
    └── README.md

```

**Environment:**
 - OS: 
Windows 11 Professional Edition
22H2
22621.1555
 - Node Version 
v18.12.0
- Crowdin Version
3.11.0

**Screenshots**

**Additional context**

**Comment by andrii-bodnar** [comment]
@xooch95 please try removing the comma here:

```diff
- "preserve_hierarchy": true,
+ "preserve_hierarchy": true
}
```

**Comment by lattechen925** [comment]
@andrii-bodnar after trying to remove the comma, the problem still persists
- Configuration file 
```yml
project_id: '123456'
api_token_env: CROWDIN_PERSONAL_TOKEN
"base_path" : "."
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    source: '/i18n/**/*',
    translation: '/i18n/%two_letters_code%/**/%original_file_name%'
  }
]
```

**Comment by andrii-bodnar** [comment]
@xooch95 could you please share your Crowdin project ID? It's better to share it by contacting our support team and mentioning this issue as a reference.

Thanks!

**Comment by andrii-bodnar** [comment]
@xooch95 also, please make sure to re-upload your source files to Crowdin (running the `crowdin upload sources` command again).

It seems like the issue is related to the wrong _Resulting file after the translations export_ due to the wrong `preserve_hierarchy` option during the first upload (https://crowdin.github.io/crowdin-cli/faq#downloaded-translations-dont-match-the-current-project-configuration)

**Comment by lattechen925** [comment]
@andrii-bodnar My crowdin project ID is 587227.

**Comment by andrii-bodnar** [comment]
@xooch95 thank you. Have you tried my recommendations from my last comment?

**Comment by lattechen925** [comment]
@andrii-bodnar I tried, but still can't

**Comment by andrii-bodnar** [comment]
@xooch95, I am happy to inform you that we have made some changes on our end to our database and changed the file export patterns for you and everything should work fine now. (the patterns were still incorrect).

Please make sure that the `preserve_hierarchy` option in the `crowdin.yml` configuration is set to `true`. The CLI will take care of everything else, you do not need to manually update the patterns on the crowdin side, it was a one-time change.

This is an example from my test project of how it should look like:

![screenshot-crowdin com-2023 05 23-09_28_57](https://github.com/crowdin/crowdin-cli/assets/29282228/811ee5f4-671f-4a0d-8ab0-41a752ed5dc0)

**Comment by lattechen925** [comment]
@andrii-bodnar  The method you mentioned is indeed feasible. But I don't want to make changes one by one on the web side. Is there any good way？

I want to configure crowdin.yml and then execute crowdin push or crowdin pull. If I have the following directory structure, how should I configure crowdin.yml correctly?

```
i18n/
├── README.md
└── core
    └── guide
       ├── README.md
       ├── intro.md
    └── README.md
```

**Comment by andrii-bodnar** [comment]
@xooch95 this is probably a Windows issue with the `**` pattern. It does not involve making manual changes on the web side. Could you please try if it works as expected on another operating system? In my case, your configuration works fine on MacOS.

**The following config should work anyway:**

```yml
# ...

"preserve_hierarchy": true

files: [
  {
  "source": "/i18n/*.md",
  "translation": "/i18n/%two_letters_code%/%original_file_name%",
 },
 {
  "source": "/i18n/core/*.md",
  "translation": "/i18n/%two_letters_code%/core/%original_file_name%",
 },
 {
  "source" : "/i18n/core/guide/*.md",
  "translation": "/i18n/%two_letters_code%/core/guide/%original_file_name%",
 },
]
```

- `crowdin push`
- `crowdin pull`

**Result:**

![Знімок екрана 2023-05-23 о 10 39 55](https://github.com/crowdin/crowdin-cli/assets/29282228/b1aa1a95-4ea3-4639-8801-d65ecb74d3fc)
