### ISSUE TITLE
3.11 broke source downloading when `source` and `dest` have different base name

### ISSUE THREAD

**Issue by yanghua-ola** [crowdin/crowdin-cli#603]
Sorry for skipping the bug template but this problem is quite straightforward. This commit https://github.com/crowdin/crowdin-cli/pull/574 introduced a bug to version 3.11. 

When
1. `source` field didn't contain any wildcard
2. base file name didn't match for `source` and `dest` field

Example `crowdin.yml`
```
...
files:
  - source: /workdir/foo/string_zh_CN.json
    translation: /workdir/foo/string_%two_letters_code%.json
    dest: /foo_string.json
    type: json
```

Then `crowdin download sources` would fail with error
```
✔️  Fetching project info     
⚠️  No sources found for '/foo_string.json' pattern. Check the source paths in your configuration file
```

Culprit is here
https://github.com/crowdin/crowdin-cli/blob/5474ec6e99ed5a178555277b71ca51804474a02f/src/main/java/com/crowdin/cli/commands/actions/DownloadSourcesAction.java#L136

Would love to contribute a PR but I don't have a Java development environment.
