### ISSUE TITLE
Receiving "Invalid range near index" when translation file path has square brackets

### ISSUE THREAD

**Issue by andrecampestrini** [crowdin/crowdin-cli#644]
**Describe the bug**

When uploading sources to Crowdin, if any of the translation files have square brackets in the path, the command will fail with the following error:

```
❌ Invalid range near index 71
/github/workspace/apps/member-portal/src/pages/accounts/savings/[account-id]/transactions/translations/.*
```

**To Reproduce**
1. Use the following config file:
```
project_id: ***
api_token_env: ***
preserve_hierarchy: true
files:
  - source: /apps/**/translations/en.json
    translation: /apps/**/translations/%two_letters_code%.json
```
2. Create a translation file in a directory or path that has square brackets 
3. Execute CLI command: `crowdin upload sources`
4. See an error

**Expected behavior**

Sources are uploaded without any issues.

**Environment:**
 - OS: Ubuntu
 - Version: [22.04](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230917.1)

**Screenshots**
N/A

**Additional context**
Error occurs when running the [Github action](https://github.com/crowdin/github-action) v1, in the "UPLOAD SOURCES" step.
