### ISSUE TITLE
Download sources finds no source files under Windows

### ISSUE THREAD

**Issue by sz-liva** [crowdin/crowdin-cli#679]
**Describe the bug**
Command `download sources` finds no source files to download.

**To Reproduce**
`list sources` works fine
```
crowdin list sources --identity .crowdin.yml --branch="releases-7.3.3"  --verbose
[OK] Fetching project info
[OK] File 'src\main\resources\translations\en\SuggestionTexts.properties'
```
but `pull sources` fails.
```
crowdin pull sources --identity .crowdin.yml --branch="releases-7.3.3"  --verbose
[OK] Fetching project info
[WARNING] No sources found for '\src\main\resources\translations\en\*' pattern. Check the source paths in your configuration file
```
The configuration is:
```yml
preserve_hierarchy: true
files:
  - source: /src/main/resources/translations/en/*
    translation: /src/main/resources/translations/%two_letters_code%/%original_file_name%
    escape_special_characters: 0
    escape_quotes: 0
    export_only_approved: true
```
I tried removing the first `/` from the `source` field in `crowdin.yml` but it didn't help.

**Expected behavior**
`crowdin list sources --identity .crowdin.yml --branch="releases-7.3.3"  --verbose` should output
```
✔️  Fetching project info
✔️  File 'src/main/resources/translations/en/SuggestionTexts.properties'
```

**Environment:**
 - OS: Windows 11 Pro
 - Version 3.15.0

**Additional context**
It works fine with Crowdin CLI 3.15.0 under Ubuntu.
