### ISSUE TITLE
Unable to upload iOS Localizable.strings

### ISSUE THREAD

**Issue by wes-nz** [crowdin/crowdin-cli#718]
**Describe the bug**

`crowdin push` returns an execution error when trying to upload an iOS Localizable.strings.

**To Reproduce**
1. Config file:
```YAML
"project_id": "XXXX"
"api_token":XXXX"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    "source": "/Sources/AppResources/en.lproj/Localizable.strings",
    "translation": "/Sources/AppResources/%two_letters_code%.lproj/Localizable.strings",
    "languages_mapping": {
      "two_letters_code": {
        "de": "de",
        "en": "en",
        "es-ES": "es",
        "fr": "fr",
        "ja": "ja",
        "pt-PT": "pt",
        "ru": "ru",
        "zh-CN": "zh-Hans",
      }
    },
```
2. Execute CLI command: '...'
`crowdin push`
4. See an error
```
✔️  Fetching project info

❌ Cannot invoke "java.util.List.stream()" because "this.directories" is null
```
**Expected behavior**
The source file should be uploaded.

**Environment:**
 - OS: macOS M1
 - Version: Sonoma 14.1.1 (23B81)

**Additional context**
I tried many different `source` and `base_path`. The verbose version of the command doesn't print more details.
Thanks.
