### ISSUE TITLE
Unify the strings: 'Approve' or 'Proofread'?

### ISSUE THREAD

**Issue by hwhsu1231** [crowdin/crowdin-cli#719]
### Suggestion

I noticed that the subcommands of `crowdin status` are:

```
COMMANDS:
  translation   Show only translation progress for a project
  proofreading  Show only proofreading progress for a project
```

However, the outputs of `crowdin status` are:

```
[OK] Fetching project info
Translated:
        - zh-CN: 0%
        - zh-TW: 0%
Approved:
        - zh-CN: 0%
        - zh-TW: 0%
```

We can see that the `Approved` is corresponding to `proofreading`.

I wonder why not unify these strings, thoroughly? (I prefer `proofread`)

That is, replace the outputs of `crowdin status` with:

```
[OK] Fetching project info
Translated:
        - zh-CN: 0%
        - zh-TW: 0%
Proofread:
        - zh-CN: 0%
        - zh-TW: 0%
```

### Versions

crowdin-cli version: 3.16.1
