### ISSUE TITLE
Downloading translations with --all clashes different export configurations

### ISSUE THREAD

**Issue by brawaru** [crowdin/crowdin-cli#724]
Initially filed at https://github.com/crowdin/github-action/issues/212.

**Describe the bug**
When downloading translations with `--all` flag and having two (or more) different export configurations for different file groups, Crowdin CLI will build translations with every configuration and download them successfully, but will override all translations of one export configuration with others of different configuration during extraction.

**To Reproduce**
1. Have two or more files with different export configurations, e.g.:
   ```yaml
   # ...
   files:
     - source: /locales/en-US/index.json
       dest: /%original_file_name%
       translation: /locales/%locale%/%original_file_name%
       skip_untranslated_strings: true
     - source: /locales/en-US/configuration.json
       dest: /%original_file_name%
       translation: /locales/%locale%/%original_file_name%
   ```
2. Try to download translations for these files: `java -jar crowdin-cli.jar download --all -c ./crowdin.yml --branch="[username.repository] main"`
3. Notice how Crowdin will extract the same file several times:
   ```
   ...
   [OK] Extracting archive
   [OK] Extracted: 'locales\en-GB\index.json'
   [OK] Extracted: 'locales\en-GB\configuration.json'
   [OK] Extracted: 'locales\uk-UA\index.json'
   [OK] Extracted: 'locales\uk-UA\configuration.json'
   [OK] Extracted: 'locales\en-GB\index.json'      << (!)
   [OK] Extracted: 'locales\en-GB\configuration.json'
   [OK] Extracted: 'locales\uk-UA\index.json'
   [OK] Extracted: 'locales\uk-UA\configuration.json'
   ```
4. Check the first downloaded file group and notice that the file is exported with a different configuration (in example, it will have all strings pre-filled, even though `skip_untranslated_strings` was set to `true`).

**Expected behavior**
As my understanding goes, `--all` should just ignore inexistence of source files when downloading translations, while adhering to the export options specified by the `crowdin.yml`.

**Environment:**
 - OS: any supported
 - Version: any supported

**Screenshots**
N/A

**Additional context**
In our case it is impossible to go without `--all` because we have source files that are generated automatically and uploaded by one GitHub workflow without pushing them to the repository while download is performed by a different workflow that doesn't generate sources. As I workaround for now you can make the fake source files, which would prevent Crowdin CLI from omitting translation files for them without the `--all` flag.
