### ISSUE TITLE
Crowdin Configuration file not using environment vars

### ISSUE THREAD

**Issue by gianlucajahn** [crowdin/crowdin-cli#774]
**Describe the bug**
When trying to use the `CROWDIN_API_TOKEN` from my `.env` file in my `crowdin.yml` file, I get the following errors:

:x: Fetching project info
:x: Failed to collect project info. Please contact our support team for help
:x: Couldn't authorize. Check your 'api_token'

**To Reproduce**

1. Configuration file: 'crowdin.yml' holds `"api_token": CROWDIN_API_TOKEN`
2. '.env' file holds `CROWDIN_API_TOKEN=123...`
3. Run CLI command `crowdin download --all`

**Expected behavior**
Translations can be downloaded the same way they can be downloaded if the api token is hardcoded into the `.yml` file.

**Environment:**
 - OS: Ubuntu
 - Version: Ubuntu 22.04.2 LTS
 - Crowdin Version: crowdin/cli:3.18.0

**Comment by andrii-bodnar** [comment]
@gianlucajahn you need to use the following options in your `crowdin.yml` file to specify the environment variables:

```yml
"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path_env": "CROWDIN_BASE_PATH"
"base_url_env": "CROWDIN_BASE_URL"
```

[API Credentials from Environment Variables](https://developer.crowdin.com/configuration-file/#api-credentials-from-environment-variables)
