### ISSUE TITLE
Detecting / deleting obsolete files not working

### ISSUE THREAD

**Issue by anbraten** [crowdin/crowdin-cli#775]
**Describe the bug**
Delete obsolete is not detecting deleted / non-existing file.

**To Reproduce**
1. Configuration file: 

```yml
preserve_hierarchy: true

files:
  # Docs Markdown files
  - source: '/test/en/**/*.md'
    translation: '/test/%two_letters_code%/**/%original_file_name%'
```

2. `tree test/`:

```bash
test/
└── en
    ├── support.md
    └── test.md

2 directories, 2 files
```

3. Execute CLI command: `npx @crowdin/cli upload sources --token ... --project-id ... --delete-obsolete --no-auto-update`
Outputs:

```bash
✔️  Fetching project info     
⏭  File 'test/en/support.md'
⏭  File 'test/en/test.md'
✔️  No obsolete files were found
✔️  No obsolete directories found
```

![image](https://github.com/crowdin/crowdin-cli/assets/6918444/7dce6008-88f5-4a87-8a31-189ab38f1383)

5. Rename file `test/en/support.md` => `test/en/help.md`
6.  Execute CLI command again: `npx @crowdin/cli upload sources --token ... --project-id ... --delete-obsolete --no-auto-update`
Outputs:

```bash
✔️  Fetching project info     
⏭  File 'test/en/test.md'
⏭  File 'test/en/help.md'
✔️  No obsolete files were found
✔️  No obsolete directories found
```

![image](https://github.com/crowdin/crowdin-cli/assets/6918444/821a68af-e45c-4e98-aa87-241588469e4d)

**Expected behavior**
I expect the file `test/en/support.md` to be detected as obsolete and deleted on Crowdin afterwards as it does not exists locally anymore.

**Environment:**
 - OS: Ubuntu
 - Version 23.04
 - Cli: @crowdin/cli@3.19.2
