### ISSUE TITLE
can't do any thing in cli

### ISSUE THREAD

**Issue by DancingSnow0517** [crowdin/crowdin-cli#846]
**Describe the bug**
when i use command `crowdin pull`
cli show the message
[ERROR] class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')

**To Reproduce**
1. Configuration file:
  ```
project_id: '720595'
#api_token_env: CROWDIN_API_TOKEN
api_token: ******
base_path: '.'

preserve_hierarchy: true

files:
  - source: 'src/generated/resources/assets/anvilcraft/lang/en_us.json'
    translation: 'src/main/resources/assets/anvilcraft/lang/%locale_with_underscore%.json'
    languages_mapping:
      locale_with_underscore:
        zh-CN: zh_cn
        zh-TW: zh_tw
        en: en_us
        be: be_by
        cs: cs_cz
        cy: cy_gb
        da: da_dk
        de: de_de
        eo: eo_uy
        es-CL: es_cl
        es-ES: es_es
        es-MX: es_mx
        et: et_ee
        fa: fa_ir
        fi: fi_fi
        fr: fr_fr
        hu: hu_hu
        id: id_id
        is: is_is
        it: it_it
        ja: ja_jp
        kk: kk_kz
        ko: ko_kr
        nl: nl_nl
        no: no_no
        pl: pl_pl
        pt-BR: pt_br
        pt-PT: pt_pt
        ro: ro_ro
        rpr: rpr
        ru: ru_ru
        sv-SE: sv_se
        th: th_th
        tok: tok
        tr: tr_tr
        uk: uk_ua
        vi: vi_vn
        lzh: lzh
        zhmeme: zh_meme

commit_message: New Crowdin translations by GitHub Action
  ```
2. Execute CLI command `crowdin pull`
3. See an error
  [ERROR] class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')

**Environment:**
 - OS: Windows11

**Screenshots**
![image](https://github.com/user-attachments/assets/b26499ee-3071-47a5-9615-c92f6e26ec83)
