### ISSUE TITLE
Error: `base path` is empty

### ISSUE THREAD

**Issue by ffflorian** [crowdin/crowdin-cli#91]
When trying to download the latest translations for my crowdin project, I get the following error:
```
$ crowdin download --identity keys/crowdin.yaml
Building ZIP archive with the latest translations for 'ro' - skipped
Error `base path` is empty
```

My config file:
```yaml
"project_identifier": "[redacted]"
"base_path": "."

files: [
  {
    "source": "/electron/locale/strings.js",
    "translation": "/electron/locale/strings-%two_letters_code%.js",
    "update_option": "update_as_unapproved"
  }
]
```

My environment:
```
OS: Linux Debian 9.5 stretch
crowdin: v2.0.24
Java: 1.8.0_191
```
