### ISSUE TITLE
Support custom languages mapping

### ISSUE THREAD

**Issue by Rustavil** [crowdin/crowdin-cli#921]
Crowdin support mapping standard language code into custom one in the Crrowdin config file.
crowdin-cli does validation of such mapping, and check if crowdin language code in the standard list of  https://developer.crowdin.com/language-codes

Problem:
If Crowdin project has custom languages, they won't pass those validation.

Example validation error:
Configuration file is invalid. Check the following parameters in your configuration file:
        - The mapping format is the following: crowdin_language_code: code_you_use. Check the full list of Crowdin language codes that can be used for mapping: https://developer.crowdin.com/language-codes.

**Comment by Rustavil** [comment]
Here you can see, only standard languages are loaded for validation https://github.com/crowdin/crowdin-cli/blob/fb9b47b778d2edfa06703805560f034f7f1ee937/src/main/java/com/crowdin/cli/properties/PropertiesWithFiles.java#L83

**Comment by andrii-bodnar** [comment]
Hi @Rustavil, Crowdin CLI supports [language mapping](https://support.crowdin.com/enterprise/project-settings/languages/#language-mapping) configured in Crowdin UI and [language mapping](https://crowdin.github.io/crowdin-cli/advanced#languages-mapping-configuration) configured in the `crowdin.yml` configuration file. These two approaches cannot be used simultaneously.

Could you please also provide your `crowdin.yml` configuration file and the command you use?

**Comment by Rustavil** [comment]
Hi, thanks for quick reaction.

We’re using only mapping via crowdin config file, and don’t use Crowdin UI for that. 

Our project has custom language codes like enee(English, Estonian) etc. Such custom codes won’t pass validation.

**Comment by andrii-bodnar** [comment]
@Rustavil could you please share your `languages_mapping` configuration from `crowdin.yml`?

**Comment by Rustavil** [comment]
```yaml
"project_id": CROWDIN_PRJOJECT_ID
"api_token": CROWDIN_API_KEY
"base_path": ""

"preserve_hierarchy": true

files: [
  {
    "source": "/application/config/src/main/resources/messages/messages.properties",
    "translation": "/application/config/src/main/resources/messages/messages_%locale_with_underscore%.properties",
    "type": "properties",
    "escape_quotes": 1,
    "escape_special_characters": 0,
    "languages_mapping": {
      "locale_with_underscore": {
        "enee": "eng_EE",
        "enlv": "eng_LV",
        "enlt": "eng_LT",
        "et": "est_EE",
        "lv": "lav_LV",
        "lt": "lit_LT",
        "ruee": "rus_EE",
        "rulv": "rus_LV",
        "rult": "rus_LT"
      }
    }
  }
]

```
